### ISSUE TITLE
Gpodder gui doesn't work in Win10

### ISSUE THREAD

**Issue by shellster** [gpodder/gpodder-core#17]
I've installed all the requirements, and gpodder gui does not appear to work in Windows 10.  There is nothing in the console if it I run it from the command line.  There is no crash output.  Running the file doesn't result in any output or any window.

**Comment by Keeper-of-the-Keys** [comment]
Hi sorry we're only looking at this now.

I'm closing this bug because gpodder-core is not the GUI, there is either the main gpodder project or gpodder-ui-qml.

If the problem still exists please report there.
