### ISSUE TITLE
Youtube parser fails to find channel feed when ID contains a "-"

### ISSUE THREAD

**Issue by lrenaud** [gpodder/gpodder-core#19]
Valid youtube ID's for channels can contain a dash character. The current youtube plugin implementation only treats alphanumerics as valid channel ID characters.

Passing generic non-rss feeds fend to fail. For example:
https://www.youtube.com/channel/UCrUXL60iLgwjMowTF-toqWA
yt:UCrUXL60iLgwjMowTF-toqWA

But a manual request explicitly to the rss feed such as the following (for the same channel) succedes.
https://www.youtube.com/feeds/videos.xml?channel_id=UCrUXL60iLgwjMowTF-toqWA

It appears that the problem is related to the regex pattern used around line 185 of /src/gpodder/plugins/youtube.py

**Comment by thp** [comment]
Can you submit a proposed patch?

**Comment by lrenaud** [comment]
It looks like I totally misdiagnosed the cause. 

The URL in question results in a call to resolve_v3_url, which in turn calls get_channels_for_user and returns no active channels.

I'm having some trouble piecing together the exact failure route. It looks like the call gets routed through a call to resolve_v3_url where it simply returns the same URL, but I'm not sure how things flow from there. The call stack suggests that it is triggered directly by a button click, but without further digging/guidance I as of yet haven't been able to find where the URL gets parsed a second time.

I know at some point a copy of thread_proc() get's called again and eventually acts on the url, but it's beyond me tonight to dig much further than that. I'll keep tinkering with this to see what I can find.

**Comment by thp** [comment]
I /think/ this is fixed by the linked commit, which is a fix that we already have in mainline gPodder 3.
