### ISSUE TITLE
What happened to user extensions?

### ISSUE THREAD

**Issue by jugdizh** [gpodder/gpodder-core#20]
According to: http://wiki.gpodder.org/wiki/Cuatro

> Contributors should be able to extend gPodder 4 in the following ways:
> Extension scripts (same as in gPodder 3, possibly with a big API overlap)

But looking through the source, I see no hook for extension scripts at all. Where did they go?

**Comment by thp** [comment]
Most of this was replaced with:

https://github.com/gpodder/gpodder-core/blob/master/src/gpodder/registry.py

and the corresponding plugins here:

https://github.com/gpodder/gpodder-core/tree/master/src/gpodder/plugins

Granted, this doesn't cover all of the extension script functionality, but then again, gPodder 4 doesn't have the gPodder 3 UI features for which most extension hooks were used.

Anything in particular that you are missing?

**Comment by jugdizh** [comment]
What would be the gPodder 4 equivalent of the following?

```
class gPodderExtension:

    def __init__(self, container):
        self.container = container
        
    def on_episode_downloaded(self, episode):
        # do custom post-download processing, id3 tags, volume normalization, etc.
```

**Comment by thp** [comment]
Yeah, that doesn't exist yet. You could add a new entry to `RESOLVER_NAMES` (https://github.com/gpodder/gpodder-core/blob/master/src/gpodder/registry.py#L68), then create a new plugin in the plugins directory that decorates your `on_episode_downloaded` function with `@registry.after_download.register`, then in https://github.com/gpodder/gpodder-core/blob/master/src/gpodder/download.py#L849 add a call to `registry.after_download.each(self.__episode)`

**Comment by jugdizh** [comment]
Wow, that was a fast patch! Thanks!!
