### ISSUE TITLE
SSL cert verification fails if file episode URL returns a 301 to another domain

### ISSUE THREAD

**Issue by schmittlauch** [gpodder/gpodder-core#21]
When I tried to download a recent [episode of the Resonator podcast](http://resonator-podcast.de/podlove/file/3054/s/feed/c/opus/RES101_Dementia_Care_Management.opus ) the download didn't even start. After looking at the stdout output of gPodder I saw it's an issue with certificate verification.
The problem occured with gpodder-sailfish 4.6 on SailfishOS 2.1.0.9

[stdout output of gPodder including a stacktrace](https://gist.github.com/schmittlauch/bfd35789afef25d9aeb9c22fe70101b4 )

I think it's the chaining of redirects and mixture of http and https links which causes the issue here. In case the setup of the podcast page changes, I document here what's currently happening:

- the feed links to the episode file via unencrypted http: `http://resonator-podcast.de/podlove/file/3054/s/feed/c/opus/RES101_Dementia_Care_Management.opus`
- this link returns an HTTP 301 permanent redirect to `https://files.wrint.de/RES101_Dementia_Care_Management.opus?ptm_source=feed&ptm_context=opus&ptm_request=84e16c95afa2&ptm_file=RES101_Dementia_Care_Management.opus` . This is a different domain and also now https encrypted
- the location redirected to works fine when opened inside a browser. It also has a valid certificate by Comodo (so no obscure CA) which is only valid for `files.wrint.de`

I suspect this unusual setup to be the cause of this issue.

**Comment by Keeper-of-the-Keys** [comment]
I suspect this was/is an issue at the system level the stacktrace involves system libraries only.

Since this was opened a long time ago and both SFOS and gPodder have moved many versions since then I am closing the issue.

If this does still occur on the current version please feel free to re-open.
