### ISSUE TITLE
handle soundcloud permissions

### ISSUE THREAD

**Issue by elelay** [gpodder/gpodder-core#25]
(opening a new to bring it out of a comment on a close PR).

Try this feed: https://soundcloud.com/user-588924363
I created it so that each track had different permissions.

When every permission is disabled (*White* track), getting track metadata fails, so the track is silently skipped (doesn't show up in gPodder).

Else, either *enable direct download*, *offline listening* or *enable app playback* is activated.
Then we always get stream and download urls.

permission | streamable | downloadable | retrieve stream_url | retrieve download_url
-------------- | -------------- | ------------------ | ----------------------- | ------------------------------
**offline listening** | False | False | 401 | 401
**enable app playback** | **True** | False | **OK** | 401
**enable direct download** | False | **True** | 401 | **OK**

**Comment by elelay** [comment]
Here is the settings dialog:
![permissions_choices](https://user-images.githubusercontent.com/222469/63227895-e7168980-c1eb-11e9-8705-e8064ed92b07.png)

**Comment by elelay** [comment]
in my opinion we should:
 - remove the `filter=downloadable` parameter from `json_url`: it's useless
 - include track only if downloadable or streamable
 - select the right url, preferring stream_url if streamable and downloadable

What do you think?

**Comment by elelay** [comment]
(begining of the discussion: https://github.com/gpodder/gpodder-core/commit/4de9773d2e9e8469b8c4f4b8ccc4a135a2d95543#commitcomment-34731558)

**Comment by elelay** [comment]
See https://github.com/gpodder/gpodder/commit/28f729f15e83d4d25b57ba8ca0312956e9a2a616 for implementation in gpodder desktop.

**Comment by Keeper-of-the-Keys** [comment]
Hi sorry about the delay.

I am unclear on one thing in your example from desktop - why is stream_url obtained with track.get('stream_url') while download_url is just obtained with track['download_url']?
Both are as far as I can tell from the JSON object always set, so using get() with failover option is needed in neither case (though probably still preferable in both cases to prevent the plugin from blowing up if someone manages to create a JSON without one or the other).

**Comment by Keeper-of-the-Keys** [comment]
I modified the plugin (will do a PR later tonight or this week) am I correct when I say that I should only have "Brown" and "Sine" as tracks?

**Comment by elelay** [comment]
@Keeper-of-the-Keys thanks for getting back to this.

> using get() with failover option is needed in neither case
yes, you're right `get()` is not needed.

> I should only have "Brown" and "Sine" as tracks?
correct

**Comment by Keeper-of-the-Keys** [comment]
> > using get() with failover option is needed in neither case
> 
> yes, you're right `get()` is not needed.
> 
Wouldn't using get() across the board be more robust though (even without the failover option)? ATM from our tests these fields are always set but if for some reason they are not set get() will allow the code to continue to run while when using a direct reference the code will crash if the field is not present.

**Comment by elelay** [comment]
Then we should check for `None` before doing `url = base_url + '?consumer_key=' + CONSUMER_KEY`

**Comment by Keeper-of-the-Keys** [comment]
I merged the fix, performance is not great as far as I can tell but we'll handle that in a separate issue for future release.
