### ISSUE TITLE
Wishlist - Add per section sources update

### ISSUE THREAD

**Issue by murrayf** [gpodder/gpodder-core#7]
Hello,

  I have a lot of sources in my gpodder program classified by sections. It would be great to implement the possibility to update each section individually without updating the whole subscriptions list.

Thanks and congratulations for gpodder!

Alberto.

:)

**Comment by thp** [comment]
Is that for the CLI or the QML UI?

**Comment by murrayf** [comment]
for UI

-----------------
Alberto Segura.

**Comment by thp** [comment]
Which OS/port? Android? BB10? Sailfish OS?

**Comment by murrayf** [comment]
Hi again,

Sorry, the linux GTK ui.

-----------------
Alberto Segura.

**Comment by thp** [comment]
Ah, ok -- that'd be https://github.com/gpodder/gpodder for which we do bug tracking on http://bugs.gpodder.org/ - can you file that feature request there?

**Comment by murrayf** [comment]
Yes, of course.

Thanks Thomas.

-----------------
Alberto Segura.

**Comment by thp** [comment]
See here: https://bugs.gpodder.org/show_bug.cgi?id=1995
